version: '3.7'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
#    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./bin/www
    command: npm start
    ports:
      - "9229:9229"
      - "9230:9230"
      - "4200:4200"
    labels:
      traefik.enable: "true"
      traefik.http.routers.node.rule: Host(`node.conduit3.com`)
      traefik.http.routers.node.entrypoints: http
      traefik.http.routers.node.service: node
      traefik.http.services.node.loadbalancer.server.port: 4200

      traefik.tcp.routers.nodered-debug.rule: Host(`node-debug.conduit3.com`) 
      traefik.tcp.routers.nodered-debug.entrypoints: http
      traefik.tcp.routers.nodered-debug.service: nodered-debug
      traefik.tcp.services.nodered-debug.loadbalancer.server.port: 9229

    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      disable: true
    networks:
      - private
    user: root
volumes:
  notused:
  nodered_projects:
  nodered_node_modules:
networks:
  public:
  private: